### ISSUE TITLE
[Suggestion] Tetra compatibility

### ISSUE THREAD

**Issue by Omni35** [illusivesoulworks/veinmining#8]
Hello, I was wondering if it's possible to make this enchantment work with tools from the mod "Tetra".

Currently, this enchantment cannot be applied in either the anvil or the Tetra workbench once a tool has been modified by that mod, although I'm unsure whether I should request this compatibility here or at the Tetra GitHub. Please correct me if it's the wrong place to ask this.

**Comment by TheIllusiveC4** [comment]
I'm also unsure whether this is done on my end or Tetra's, but I'll look into it.
